### ISSUE TITLE
[FEATURE REQUEST] RESTORE HALAMAN LOGIN

### ISSUE THREAD

**Issue by chelsymooy** [budi7/gantiRugi#1]
**MENAMBAHKAN TAGLINE**
Solusi berasuransi Zaman Now

**Comment by agilma** [comment]
- [x] ganti tulisan ganti rugi ke logonya ganti rugi

**Comment by budi7** [comment]
fixed [3.3.11](https://github.com/budi7/gantiRugi/releases/tag/TEST-3.3.11)
