### ISSUE TITLE
[BUG] SETELAH AKTIFKAN PROTEKSI PROMO, OPSI MASIH MUNCUL DI MENU QUOTATION

### ISSUE THREAD

**Issue by chelsymooy** [budi7/gantiRugi#2]
Promo sudah diaktifkan, tapi pilihan proteksi 20 masih muncul

akun:
mooychelsy@hotmail.com
admin123

**Comment by budi7** [comment]
fixed [3.3.11](https://github.com/budi7/gantiRugi/releases/tag/TEST-3.3.11)
