### ISSUE TITLE
DOKUMEN PENAWARAN

### ISSUE THREAD

**Issue by chelsymooy** [budi7/gantiRugi#3]
![image](https://user-images.githubusercontent.com/5895063/60708710-e32ef080-9f38-11e9-8cc8-55ec84f06af9.png)

Butuh menu untuk download penawaran (contoh di gambar atas)
Data link diperoleh dari quotation index/ show, field penawaran_link (lihat gambar bawah)

![image](https://user-images.githubusercontent.com/5895063/60708860-3739d500-9f39-11e9-845d-d27cfc5fa726.png)

**Comment by budi7** [comment]
UPDATED 0.3.2
